### ISSUE TITLE
[Bug]:error generating epg.xml 

### ISSUE THREAD

**Issue by Tezzlicious** [Josh5/TVH-IPTV-Config#5]
### Describe the Bug

After adding channels the epg.xml returns the following error in the browser:

```
This page contains the following errors:

error on line 5 at column 8: Couldn't find end of Start Tag icon
Below is a rendering of the page up to the first error.
```

On the server the epg.xml stops at the first channel icon tag:
```

<?xml version='1.0' encoding='UTF-8'?>
<tv generator-info-name="TVH-IPTV-Config" source-info-name="TVH-IPTV-Config - v0.1">
	<channel id="1000_Channel1">
		<display-name>Channel 1</display-name>
		<icon
```

In the database the logo_url column in table channels is NULL.

The logo column during channel selection (Import channels from playlist --> Select Stream From Playlist) is empty.

I also noticed that on the Channel Details view, the section after channel name keeps skeleton loading. Am I supposed to see some kind of logo info?:

![image](https://github.com/Josh5/TVH-IPTV-Config/assets/17005983/69acd85d-9b83-4f94-9886-fa7ce3e3af74)

Because of this the whole EPG for all channels stays empty.

Thanks for you efforts and keep up the good work.

### Steps to Reproduce

1. Add M3U playlist.
2. Add EPG xmltv url.
3. Import some channels and link EPG.

### Expected Behavior

EPG should be generated ok and logo should be selectable or used from TVH.

### Version

josh5/tvh-iptv:latest

### Platform

Docker: josh5/tvh-iptv:latest 

Running Unraid OS.

**Comment by Josh5** [comment]
This was likely caused by a thread lock on the application. The recent improvements to the app should hopefully preventing things like this.
Ultimately, the application cannot read from the database if a large EPG or playlist is in the process of being imported. It gets into a locked state and then if you refresh the web interface, it may fail to load certain things because the request for the config from the database failed.
